### ISSUE TITLE
The `vnujar` should be updated

### ISSUE THREAD

**Issue by Jayman2000** [svenkreiss/html5validator#113]
When I try to validate this CSS:

```css
:not(p, a)
{
        color: red;
}
```

Html5validator gives me:

```
"file:<path>/example.css":1.6-1.6: error: CSS: Parse Error.
"file:<path>/example.css":4.2-5.1: error: CSS: Parse Error.
```

[V.Nu’s Web interface](https://validator.w3.org/nu/) reports no errors with that CSS.
