### ISSUE TITLE
add missing CSS Property "text-decoration-thickness"

### ISSUE THREAD

**Issue by MFTabriz** [svenkreiss/html5validator#116]
Whenever I'm running the html5validator on css files like:

```css
.test {
    text-decoration-thickness: 20%;
}
```

I get: `error: CSS: "text-decoration-thickness": Property "text-decoration-thickness" doesn't exist.`

related: validator/validator#1154
